services:
  openairesearch:
    image: ${DOCKER_REGISTRY-}openairesearch
    env_file: compose.local.env
    build:
      context: .
      dockerfile: openAIResearch/Dockerfile
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
