services:
  openairesearch:
    image: ${DOCKER_REGISTRY-}openairesearch
    env_file: compose.local.env
    build:
      context: .
      dockerfile: openAIResearch/Dockerfile
  postgres:
    image: ankane/pgvector
    container_name: postgres_db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./openAIResearch/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres_data:
